# Generated by Django 4.2.6 on 2023-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_dish_name_dish_restaurant_dish_review_dish_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
