# Generated by Django 4.2.6 on 2023-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_dish_options_alter_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
