# Generated by Django 4.2.6 on 2023-11-14 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_dish_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
