# Generated by Django 4.2.6 on 2023-11-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_dish_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
    ]
